### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by MachineITSvcs** [Splitit/Splitit.Plugins.WooCommerce.FF#25]
I received the following fatal error in my error log:

`PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get_id() on null in /web/wp-content/plugins/splitit-installment-payments/splitIt-flexfields-payment-gateway.php:556\nStack trace:\n#0 /web/wp-includes/class-wp-hook.php(303): WC_SplitIt_FlexFields_Payment_Gateway->splitit_add_installment_plan_number_data_thank_you_title()\n#1 /web/wp-includes/plugin.php(189): WP_Hook->apply_filters()\n#2 /web/wp-content/plugins/woocommerce/templates/checkout/thankyou.php(84): apply_filters()\n#3 /web/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/web/wp-content...')\n#4 /web/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(256): wc_get_template()\n#5 /web/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-s...`

Unfortunately the error message was truncated so I can't provide the rest of the trace, but the error is likely that the $order object is not valid/is null when being used in the splitit_add_installment_plan_number_data_thank_you_title() function when called from the woocommerce thank you page filter. Can you add a check if($order) before attempting to set $order_info. This would prevent the error and only add the text if $order object is valid.

**Comment by oleksiyzestlogic** [comment]
The issue has been fixed in the latest versions
